spring:
  application:
    name: healthcheck-service

healthcheck:
  services:
    - name: report-service
      url: ${REPORT_SERVICE_URL:http://report-service:8080/healthcheck}
    - name: storage-service
      url: ${STORAGE_SERVICE_URL:http://storage-service:8080/v1/api/healthcheck}
    - name: summary-service
      url: ${SUMMARY_SERVICE_URL:http://summary-service:8080/api/summary/healthcheck}
    - name: minio
      url: ${MINIO_URL:http://minio:9000/minio/health/live}
    - name: kafka
      host: ${KAFKA_HOST:kafka}
      port: ${KAFKA_PORT:9092}
    - name: postgres
      host: ${POSTGRES_HOST:postgres}
      port: ${POSTGRES_PORT:5432}
