spring:
  application:
    name: healthcheck-service

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:}
  chat-id: ${TELEGRAM_CHAT_ID:}

healthcheck:
  interval-ms: ${CHECK_INTERVAL_MS:120000}
  services:
    - name: report-service
      url: ${REPORT_SERVICE_URL:http://report-service:8080/healthcheck}
    - name: storage-service
      url: ${STORAGE_SERVICE_URL:http://storage-service:8080/v1/api/healthcheck}
    - name: summary-service
      url: ${SUMMARY_SERVICE_URL:http://summary-service:8080/api/summary/healthcheck}
    - name: minio
      url: ${MINIO_URL:http://minio:9000/minio/health/live}
    - name: kafka
      host: ${KAFKA_HOST:kafka}
      port: ${KAFKA_PORT:9092}
    - name: postgres
      host: ${POSTGRES_HOST:postgres}
      port: ${POSTGRES_PORT:5432}
