/*
 * This file is generated by jOOQ.
 */
package ru.bre.storage.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.bre.storage.jooq.tables.Feedback;
import ru.bre.storage.jooq.tables.Report;
import ru.bre.storage.jooq.tables.Summary;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_FEEDBACK_CREATED_AT = Internal.createIndex(DSL.name("idx_feedback_created_at"), Feedback.FEEDBACK, new OrderField[] { Feedback.FEEDBACK.CREATED_AT }, false);
    public static final Index IDX_FEEDBACK_TITLE = Internal.createIndex(DSL.name("idx_feedback_title"), Feedback.FEEDBACK, new OrderField[] { Feedback.FEEDBACK.TITLE }, false);
    public static final Index IDX_REPORT_CREATED_AT = Internal.createIndex(DSL.name("idx_report_created_at"), Report.REPORT, new OrderField[] { Report.REPORT.CREATED_AT }, false);
    public static final Index IDX_REPORT_TITLE = Internal.createIndex(DSL.name("idx_report_title"), Report.REPORT, new OrderField[] { Report.REPORT.TITLE }, false);
    public static final Index IDX_SUMMARY_CREATED_AT = Internal.createIndex(DSL.name("idx_summary_created_at"), Summary.SUMMARY, new OrderField[] { Summary.SUMMARY.CREATED_AT }, false);
    public static final Index IDX_SUMMARY_DATE = Internal.createIndex(DSL.name("idx_summary_date"), Summary.SUMMARY, new OrderField[] { Summary.SUMMARY.DATE }, false);
    public static final Index IDX_SUMMARY_TITLE = Internal.createIndex(DSL.name("idx_summary_title"), Summary.SUMMARY, new OrderField[] { Summary.SUMMARY.TITLE }, false);
}
