/*
 * This file is generated by jOOQ.
 */
package ru.bre.storage.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.bre.storage.jooq.tables.Databasechangeloglock;
import ru.bre.storage.jooq.tables.Feedback;
import ru.bre.storage.jooq.tables.Report;
import ru.bre.storage.jooq.tables.Summary;
import ru.bre.storage.jooq.tables.records.DatabasechangeloglockRecord;
import ru.bre.storage.jooq.tables.records.FeedbackRecord;
import ru.bre.storage.jooq.tables.records.ReportRecord;
import ru.bre.storage.jooq.tables.records.SummaryRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, DSL.name("databasechangeloglock_pkey"), new TableField[] { Databasechangeloglock.DATABASECHANGELOGLOCK.ID }, true);
    public static final UniqueKey<FeedbackRecord> FEEDBACK_PKEY = Internal.createUniqueKey(Feedback.FEEDBACK, DSL.name("feedback_pkey"), new TableField[] { Feedback.FEEDBACK.ID }, true);
    public static final UniqueKey<ReportRecord> REPORT_PKEY = Internal.createUniqueKey(Report.REPORT, DSL.name("report_pkey"), new TableField[] { Report.REPORT.ID }, true);
    public static final UniqueKey<SummaryRecord> SUMMARY_PKEY = Internal.createUniqueKey(Summary.SUMMARY, DSL.name("summary_pkey"), new TableField[] { Summary.SUMMARY.ID }, true);
}
