/*
 * This file is generated by jOOQ.
 */
package ru.bre.storage.jooq;


import ru.bre.storage.jooq.tables.Databasechangelog;
import ru.bre.storage.jooq.tables.Databasechangeloglock;
import ru.bre.storage.jooq.tables.Feedback;
import ru.bre.storage.jooq.tables.Report;
import ru.bre.storage.jooq.tables.Summary;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.feedback</code>.
     */
    public static final Feedback FEEDBACK = Feedback.FEEDBACK;

    /**
     * The table <code>public.report</code>.
     */
    public static final Report REPORT = Report.REPORT;

    /**
     * The table <code>public.summary</code>.
     */
    public static final Summary SUMMARY = Summary.SUMMARY;
}
