/*
 * This file is generated by jOOQ.
 */
package ru.bre.storage.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.bre.storage.jooq.Indexes;
import ru.bre.storage.jooq.Keys;
import ru.bre.storage.jooq.Public;
import ru.bre.storage.jooq.tables.records.ReportRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Report extends TableImpl<ReportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.report</code>
     */
    public static final Report REPORT = new Report();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReportRecord> getRecordType() {
        return ReportRecord.class;
    }

    /**
     * The column <code>public.report.id</code>.
     */
    public final TableField<ReportRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.report.title</code>.
     */
    public final TableField<ReportRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.report.text</code>.
     */
    public final TableField<ReportRecord, String> TEXT = createField(DSL.name("text"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.report.image_file</code>.
     */
    public final TableField<ReportRecord, String> IMAGE_FILE = createField(DSL.name("image_file"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>public.report.log_file</code>.
     */
    public final TableField<ReportRecord, String> LOG_FILE = createField(DSL.name("log_file"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>public.report.created_at</code>.
     */
    public final TableField<ReportRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Report(Name alias, Table<ReportRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Report(Name alias, Table<ReportRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.report</code> table reference
     */
    public Report(String alias) {
        this(DSL.name(alias), REPORT);
    }

    /**
     * Create an aliased <code>public.report</code> table reference
     */
    public Report(Name alias) {
        this(alias, REPORT);
    }

    /**
     * Create a <code>public.report</code> table reference
     */
    public Report() {
        this(DSL.name("report"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REPORT_CREATED_AT, Indexes.IDX_REPORT_TITLE);
    }

    @Override
    public Identity<ReportRecord, Integer> getIdentity() {
        return (Identity<ReportRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReportRecord> getPrimaryKey() {
        return Keys.REPORT_PKEY;
    }

    @Override
    public Report as(String alias) {
        return new Report(DSL.name(alias), this);
    }

    @Override
    public Report as(Name alias) {
        return new Report(alias, this);
    }

    @Override
    public Report as(Table<?> alias) {
        return new Report(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Report rename(String name) {
        return new Report(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Report rename(Name name) {
        return new Report(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Report rename(Table<?> name) {
        return new Report(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Report where(Condition condition) {
        return new Report(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Report where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Report where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Report where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Report where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Report where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Report where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Report where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Report whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Report whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
